msm: camera: smmu_api: handle NULL pointers
Stability hardening, failure to load cam_icp driver
can result in kernel panic.

Specifically, the api will never reach the log message
  Error: Cannot find name icp or all handle exist
because it will hit a NULL name pointer on the way.

  CAM_ERR: CAM-ICP: cam_icp_mgr_init_devs: 5345 no child device
  Unable to handle kernel NULL pointer dereference at virtual address 0000000000000000
  Internal error: Oops: 96000006 [#1] PREEMPT SMP
  Process init (pid: 1, stack limit = 0xffffff8008058000)
  CPU: 6 PID: 1 Comm: init Tainted: G S                4.19.79+ #1
  Hardware name: Qualcomm Technologies, Inc. kona MTP (DT)
  pstate: 20400005 (nzCv daif +PAN -UAO)
  pc : __pi_strcmp+0x88/0x154
  lr : cam_smmu_get_handle+0x74/0x41c [cam_smmu_api]
  . . .
  Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b

Turns into

  CAM_ERR: CAM-ICP: cam_icp_mgr_init_devs: 5345 no child device
  CAM_ERR: CAM-SMMU: cam_smmu_create_add_handle_in_table: 718 Error: Cannot find name icp or all handle exist
  . . .
  CAM_ERR: CAM-SMMU: cam_smmu_get_handle: 2015 Error: icp get handle fail
  CAM_ERR: CAM-ICP: cam_icp_hw_mgr_init: 5546 get mmu handle failed: -22
  CAM_ERR: CAM-ICP: cam_icp_probe: 178 ICP HW manager init failed: -22
  cam_icp: probe of soc:qcom,cam-icp failed with error -22
  . . .

SideEffects: loose logged list of modules at point of failure.

Signed-off-by: Mark Salyzyn <salyzyn@google.com>
Bug: 145594808
Test: failure to load cam_icp does not result in kernel panic
Change-Id: Ia302f23fe20f8c79ff8a0dd5426cd92e2e3ee13b